#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.C28_large{1,0,18.1,4
#
main_file.x28L: package/cfg/main_file.x28L.mak

clean::
	-$(RM) package/cfg/main_file.x28L.mak
